table dim_locations
	lineageTag: cbf34e1e-6e1d-4588-ad54-f04b6f0c43fa

	column location_id
		dataType: string
		isKey
		lineageTag: 0b683c48-09be-49be-be52-cebcfb698157
		summarizeBy: none
		sourceColumn: location_id

		annotation SummarizationSetBy = Automatic

	column location_name
		dataType: string
		lineageTag: 48060e7d-5ea7-4bcf-b052-5d6774145b28
		summarizeBy: none
		sourceColumn: location_name

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 4b0afbfb-6947-44a2-97b5-87b442adf4b3
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 72de9891-cc02-4310-89d2-04f855004e26
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 90405af5-2d17-4fa1-9c70-1147b3cfb2c3
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column market_tier
		dataType: string
		lineageTag: f33277fa-98ae-4b51-a246-24b439061d0a
		summarizeBy: none
		sourceColumn: market_tier

		annotation SummarizationSetBy = Automatic

	column seating_capacity
		dataType: int64
		formatString: 0
		lineageTag: bddd8792-07f9-4722-a681-cf7b82813057
		summarizeBy: sum
		sourceColumn: seating_capacity

		annotation SummarizationSetBy = Automatic

	column drive_thru
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b6738726-7a18-49f3-a9fb-62229e60fc39
		summarizeBy: none
		sourceColumn: drive_thru

		annotation SummarizationSetBy = Automatic

	column sq_ft
		dataType: int64
		formatString: #,0
		lineageTag: 584bed00-e00a-4ffc-8f10-086723d03bfa
		summarizeBy: sum
		sourceColumn: sq_ft

		annotation SummarizationSetBy = Automatic

	column open_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 10207ad6-6803-40e3-a133-4e8f5bee0e01
		summarizeBy: none
		sourceColumn: open_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_locations = m
		mode: import
		queryGroup: Dimension
		source =
				let
				    Source = Csv.Document(File.Contents(p_data_folder & "dim_locations.csv"), [Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"location_id", type text}, {"location_name", type text}, {"city", type text}, {"state", type text}, {"region", type text}, {"market_tier", type text}, {"seating_capacity", Int64.Type}, {"drive_thru", type logical}, {"sq_ft", Int64.Type}, {"open_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

